baseURL = 'https://blog.skydrift.cn/'
languageCode = 'zh'
title = "给时光以生命"
#theme = 'hugo-onyx-theme:'
#theme = 'capsule'
theme = 'hugo-book'
toc = true

[params]
    # BookMenuBundle = '/menu'
    math = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]